name: test


on:
  push:
    paths-ignore: [ '**.md' ]


jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ 3.7, 3.8, 3.9 ]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Tap
        run: poetry install

      - name: Run Tests
        env:
          TAP_STRIPE_API_KEY: ${{ secrets.TAP_STRIPE_API_KEY }}
        run: poetry run pytest
